services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres-db
    environment:
      - 'POSTGRES_DB=desafio'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=jhonny'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "jhonny", "-d", "desafio" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  app:
      build: .
      container_name: desafio-tecnico
      restart: always
      depends_on:
        postgres:
          condition: service_healthy
        rabbitmq:
          condition: service_started
      ports:
         - "8080:8080"
      environment:
        - DB_HOST=postgres
        - DB_NAME=desafio
        - DB_PASSWORD=secret
        - DB_PORT=5432
        - DB_USER=jhonny
        - RABBITMQ_HOST=rabbitmq
        - RABBITMQ_PORT=5672
        - RABBITMQ_USER=admin
        - RABBITMQ_PASSWORD=admin